---
title: "survey data import and harmonization for mid-Atlantic process models"
author: "Alexa Fredston-Hermann"
date: "5/7/2020"
output: html_document
---

Updating the `process_survey_data.R` file just for fluke to no longer pre-process for stages but still clean up and tidy data... 

```{r packages and functions, eval=TRUE, echo=FALSE, results=FALSE, message=FALSE}
#library(PBSmapping)
library(tidyverse)
library(here)
library(stringr)
library(lubridate)
#library(data.table)
here <- here::here

OApath <- "~/github/OceanAdapt_9815545/"
sppOfInt <- c("Paralichthys dentatus")
regOfInt <- c("Northeast US Fall")

```


# Get zero-inflated data from OceanAdapt, and other datasets
```{r data, eval=TRUE, echo=FALSE, results=FALSE, message=FALSE}
 load(paste0(OApath,"data_clean/dat_exploded.Rdata"))

```

# Get length-frequency data from individual surveys

## Northeast US

```{r neus len, eval=TRUE, echo=FALSE, results=FALSE, message=FALSE}
load(paste0(OApath,"data_raw/neus_Survdat.RData"))
load(paste0(OApath, "data_raw/neus_SVSPP.RData"))


# creating a separate haul info dataframe to get the date and btemp
hauldat <- survdat %>% 
  # create a haulid for joining
  mutate(haulid = paste(formatC(CRUISE6, width=6, flag=0), formatC(STATION, width=3, flag=0), formatC(STRATUM, width=4, flag=0), sep='-')) %>% 
  select(haulid, BOTTEMP, YEAR, EST_TOWDATE, LAT, LON) %>% 
  distinct() %>%
  rename("btemp"=BOTTEMP,
         "year"=YEAR,
         "date"=EST_TOWDATE,
         "lat"=LAT,
         "lon"=LON)

# get the dat.exploded for just this region
dat_exploded_reg <- dat.exploded %>% 
  filter(region %in% regOfInt) 

# tidy length data
len_fluke_prep <- survdat %>% 
  # create a haulid for joining with dat.exploded
  mutate(haulid = paste(formatC(CRUISE6, width=6, flag=0), formatC(STATION, width=3, flag=0), formatC(STRATUM, width=4, flag=0), sep='-')) %>% 
  select(haulid, SVSPP, LENGTH, NUMLEN) %>% 
  left_join(spp, by="SVSPP") %>% # get species names from species codes
  mutate(spp = str_to_sentence(SCINAME)) %>% # change to format of sppOfInt
  select(spp, haulid, LENGTH, NUMLEN) %>%
  filter(!is.na(LENGTH),
         spp==sppOfInt,
         LENGTH>4 # get rid of a single fish at 4cm -- the next smallest is 9cm
         ) %>% 
  rename("length"=LENGTH,
         "number_at_length"=NUMLEN)

# need to create length df that still includes zeroes
len_fluke <- expand.grid(haulid=unique(dat_exploded_reg$haulid), length=seq(min(len_fluke_prep$length), max(len_fluke_prep$length), 1)) %>% # get full factorial of every haul * length bin
  mutate(spp = sppOfInt) %>% 
  left_join(len_fluke_prep, by=c('length','haulid','spp')) %>% 
  mutate(number_at_length = replace_na(number_at_length, 0)) %>%  # fill in absences with true zeroes
  left_join(hauldat)
  
write_csv(len_fluke, here("processed-data","fluke_catch_at_length_fall.csv"))
```
