---
title: "stage-example"
author: "Dan Ovando"
date: "1/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Simulate a population with some mean recruitment with noise, a few ages (assume death after max age, should change to plus-group later)

```{r}
set.seed(42)
library(tidyverse)
library(rstan)
library(tidybayes)
library(bayesplot)
library(ggridges)
library(here)

patches <- 10

m <- 0.2

stages <- 3

years <- 100

alpha <- 0.5

sigma_r <- 0.2

years_train <- 80

years_proj <- 20  
  
mean_rec <- rlnorm(patches, log(20),1)

hist(mean_rec)


no <- mean_rec * matrix(rep(exp(-m * (0:(stages - 1))),patches), nrow = patches, ncol = stages, byrow = TRUE)

# generate data

pop <- array(NA, dim = c(patches, stages, years))

pop[,,1] <- round(no)

for (y in 2:years){
  
  pop[,1,y] <- round(mean_rec * exp(rnorm(patches,-sigma_r^2/2, sigma_r))) # add recruits
  
  pop[,2:stages,y] <-   round(pop[,1:(stages-1),y-1] * exp(-m))
  
}

proj_init <- 

pop %>% 
  reshape::melt(varnames = c("patch","stage","year")) %>% 
  as.data.frame() %>% 
  ggplot(aes(stage, value, color = factor(year))) + 
  geom_density(stat = "identity") + 
  facet_wrap(~patch)

ggpop <- pop %>% 
  reshape::melt(varnames = c("patch","stage","year")) %>% 
  as.data.frame() %>% 
  ggplot(aes(x=year, y=value, color=stage)) + 
  geom_line() + 
  facet_wrap(~patch) +
  labs(title="simulated data")

ggsave(ggpop, filename=here("results","stage_ar_model_data.png"), height=6, width=7)

# split training and testing
pop_proj <- pop[,,(years_train+1):years]

pop <- pop[,,1:years_train]

```


fit model

```{r}

stage_data <- list(
  m = m,
  np = patches,
  ns = stages,
  ny = years_train,
  n_p_s_y = pop,
  proj_init = pop[,,years_train],
  ny_proj = years_proj
)

warmups <- 1000

total_iterations <- 2000

max_treedepth <-  12

n_chains <-  4

n_cores <- 4 


stage_model_fit <- stan(file = here::here("src","stage_ar_model.stan"),
           data = stage_data,
           chains = n_chains,
           warmup = warmups,
           iter = total_iterations,
           cores = n_cores,
           refresh = 250,
           control = list(max_treedepth = max_treedepth,
                          adapt_delta = 0.95))


```

Evaluate the model 

```{r}



mean_recruits_hat <- tidybayes::gather_draws(stage_model_fit, mean_recruits[patch], n = 1000)

mean_recruits <- tibble(patch = 1:patches, mean_recruits = mean_rec)

mean_recruits %>% 
  ggplot() + 
  geom_boxplot(data = mean_recruits_hat, aes(patch, .value, group = patch)) +
  geom_point(aes(patch, mean_recruits, color = "true"), size = 2) + 
  scale_y_continuous(name = "Mean Recruits") + 
  scale_x_continuous(name = "Patch")


n_p_s_y_hat <-  tidybayes::gather_draws(stage_model_fit, n_p_s_y_hat[patch, stage,year], n = 1000)

pp_n_p_s_y_hat <-  tidybayes::gather_draws(stage_model_fit, pp_n_p_s_y_hat[patch, stage,year], n = 1000)

pp_proj_n_p_s_y_hat <-  tidybayes::gather_draws(stage_model_fit, pp_proj_n_p_s_y_hat[patch, stage,year], n = 1000)

n_p_s_y <- pop %>% 
  reshape::melt(varnames = c("patch","stage","year")) %>% 
  as_tibble() 


n_p_s_y_proj <- pop_proj %>% 
  reshape::melt(varnames = c("patch","stage","year")) %>% 
  as_tibble() 
# 
# eg_patch <- 10
# 
# n_p_s_y_hat %>% 
#   filter(patch == eg_patch) %>% 
#   ggplot() +
#    stat_lineribbon(aes(x = stage, y = .value),.width = c(.9, .6)) +
#   geom_point(data = n_p_s_y %>% filter(patch == eg_patch), aes(stage, value, color = "true")) +
#   facet_wrap(~year, scales = "free") + 
#   scale_y_continuous(name = "Numbers") + 
#   labs(caption = glue::glue("for patch {eg_patch}"))


gg_n_p_s_y_hat <- n_p_s_y_hat %>% 
  ggplot() +
  stat_lineribbon(aes(x = year, y = .value, group=stage),.width = c(.99, .95, .8, .5), color = "red") +
  geom_point(data = n_p_s_y, aes(x=year, y=value, group=stage), size = 2,alpha = 0.5) + 
  facet_grid(patch~stage, scales = "free_y") + 
  scale_fill_brewer() +
  labs(title="model predictions")

# posterior predictive fits
gg_pp_n_p_s_y_hat <- pp_n_p_s_y_hat %>% 
  ggplot() +
  stat_lineribbon(aes(x = year, y = .value, group=stage),.width = c(.99, .95, .8, .5), color = "red") +
  geom_point(data = n_p_s_y, aes(x=year, y=value, group=stage), size = 2,alpha = 0.5) + 
  facet_grid(patch~stage, scales = "free_y") + 
  scale_fill_brewer()+
  labs(title="posterior predictive fit")

# forecast fits
gg_pp_proj_n_p_s_y_hat <- pp_proj_n_p_s_y_hat %>% 
  ggplot() +
  stat_lineribbon(aes(x = year, y = .value, group=stage),.width = c(.99, .95, .8, .5), color = "red") +
  geom_point(data = n_p_s_y_proj, aes(x=year, y=value, group=stage), size = 2,alpha = 0.5) + 
  facet_grid(patch~stage, scales = "free_y") + 
  scale_fill_brewer() +
  labs(title="forecast")

ggsave(gg_n_p_s_y_hat, filename=here("results","stage_ar_model_fit.png"), width=7, height=10)
ggsave(gg_pp_n_p_s_y_hat, filename=here("results","stage_ar_model_pp.png"), width=7, height=10)
ggsave(gg_pp_proj_n_p_s_y_hat, filename=here("results","stage_ar_model_proj.png"), width=7, height=10)
```



```{r}
# plot(model1_fit, pars = c("alpha","sigma_r"))
```



