---
title: "hierarchical_model"
author: "Alexa Fredston-Hermann and Malin Pinsky"
date: "10/30/2020"
output: html_document
---

Credit to https://arxiv.org/src/2002.02001v1/anc/Appendix_S1.pdf p. 72


```{r, eval=TRUE}
library(rjags)
library(tidyverse)
library(here)
library(MCMCvis)
#library(SESYNCBayes) # for comparing to class notes 

dogfish <- read_csv(here("processed-data","dogfish_prepped_data.csv"))

dogfishTest <- dogfish %>% 
  filter(lengthclass=="adult") %>% 
  group_by(year) %>% 
  summarise(estN = sum(numlengthclass),
            haulN = length(unique(haulid))) %>% 
  arrange(year) %>% 
  mutate(estNlag = lag(estN, n=1)) %>% # create N-1 column for model
  filter(year > min(year)) 

```

Specify model structure


``` {r JAGS1, eval = TRUE, include = TRUE, echo = TRUE}

toyJags <- " 
model {
  
  # priors
  r ~ dnorm(r.hyper.a,r.hyper.b)
  K ~ dunif(K.hyper.a,K.hyper.b)
  sdo ~ dunif(sdo.hyper.a,sdo.hyper.b)
  
  # sd to precision
  obs.precision <- 1/(sdo*sdo)
  
  # process model
  N[1] ~ dpois(z0) # first time step based on known z0
  for(t in 2:lenT) { # remaining timesteps
    
    lambda[t] <- N[t-1] * exp(r - r * N[t-1] / K)  # Ricker growth 

    N[t] ~ dpois(round(lambda[t])) # process error
  
  }
  
  # observation model
  for(t in 1:lenT){
    y[t] ~ dnorm(N[t],obs.precision)
  }
} 

"
```

This takes a couple minutes to run on my laptop.

``` {r run JAGS1, eval = TRUE, include = TRUE, echo = TRUE}
dataJags <- list(lenT=nrow(dogfishTest), y=as.double(dogfishTest$estN), z0=round(mean(dogfishTest$estN[1])), 
                 sdo.hyper.a=0.1, sdo.hyper.b=10000,
                 r.hyper.a=1, r.hyper.b=1,
                 K.hyper.a=1, K.hyper.b=100000)

# Set up initial values for each chain
ncJags <- 3
initvalJags <- list()
for(i in 1:ncJags) {
  sdoinit <- runif(1, min=dataJags$sdo.hyper.a,
                   max=dataJags$sdo.hyper.b)
  rinit <- rnorm(1, mean=dataJags$r.hyper.a,
                   sd=dataJags$r.hyper.b)
  Kinit <- runif(1, min=dataJags$K.hyper.a,
                   max=dataJags$K.hyper.b)
  Ninit <- numeric(dataJags$lenT)
  Ninit[1] <- rpois(1, dataJags$z0)
  for(t in 2:dataJags$lenT) {
    Ninit[t] <-rpois(1, Ninit[t-1])
  }
  initvalJags[[i]] <- list(N=Ninit)
}

# define chain lengths
burnJags <- 1000
inferJags <- 100000

# Call to JAGS
set.seed(1)
mJags <- jags.model(file=textConnection(object=toyJags),
                      data=dataJags,
                      inits=initvalJags,
                      n.chains=ncJags)
update(mJags, n.iter = burnJags)
jagsVarM <- c("N", "sdo", "r", "K")
fJags <- coda.samples(mJags,
                        variable.names=jagsVarM,
                        n.iter=inferJags)
#MCMCsummary(fJags)
MCMCplot(fJags, params = "sdo")
MCMCplot(fJags, params = "r")
MCMCplot(fJags, params = "K")
MCMCplot(fJags, params = "N")
MCMCtrace(fJags, params = 'N\\[10\\]', pdf = FALSE, ISB = FALSE)
```

```{r plot estimates and data}
# get mean state estimates
zsJags <- apply(as.matrix(fJags)[,paste0("N[",1:dataJags$lenT,"]")],2,mean)

plot(1:dataJags$lenT, dataJags$y,
     pch=3, cex = 0.8, col=grey(0.4), ty="o",
     xlab = "t", ylab = expression(N[t]),
     xlim = c(0,dataJags$lenT),
     las = 1)
points(1:dataJags$lenT, zsJags, cex=0.6, col="blue", pch=19)
legend("top",
       legend = c("Obs", "Smooth states"),
       pch = c(3, 19),
       col = c("black", "blue"),
       horiz=TRUE, bty="n", cex=0.9)
```